### ISSUE TITLE
what is the meanning of expected dCt

### ISSUE THREAD

**Issue by appale04** [metalhelix/spikein_analysis#1]
Hi Jim
    I am just wondering that what exactly the meaning of the parameter :expected dCt in the expected txt file?

**Comment by vlandham** [comment]
Can't remember exactly. Its been a while since i looked at it. I believe the pdf associated with these spikens had this data - so i was just encoding them in a machine readable manner. 

From what I can tell, dCt is not currently being used in the analysis.
